const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');const {chromium}=require('C:/Users/leo_v/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const repo=path.resolve(__dirname,'..');
(async()=>{const server=http.createServer((req,res)=>{const f=req.url==='/'?'index.html':req.url.split('?')[0].slice(1);if(!['index.html','sw.js','manifest.webmanifest','icon.svg'].includes(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.svg')?'image/svg+xml':'application/json');res.end(fs.readFileSync(path.join(repo,f)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true,channel:'msedge'});const ctx=await browser.newContext({viewport:{width:390,height:844}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+server.address().port);
 async function create(name){await p.locator('#nuevoNom').fill(name);await p.locator('#nuevoPin').fill('1234');await p.getByRole('button',{name:'Crear y entrar',exact:true}).click();}
 async function login(){await p.locator('#selPin').fill('1234');await p.getByRole('button',{name:'Entrar 🍀',exact:true}).click();}
 await create('Orden de Leo');const uid=await p.evaluate(()=>estUid()),base=await p.evaluate(()=>CONTENIDO.materias.map(m=>m.id));assert.equal(await p.locator('#ordenMateria').count(),1);assert.equal(await p.locator('#ordenMateria option').count(),10);
 const plan=['m_historia','m_logistica','m_lre'];for(const [i,id] of plan.entries()){await p.locator('#ordenMateria').selectOption(id);assert.equal(await p.locator('.orden-lista li').count(),i+1);assert.equal(await p.locator('.materia').nth(i).getAttribute('onclick'),"abrirMateria('"+id+"')");assert.equal(await p.locator('.materia').nth(i).locator('.orden-numero').innerText(),(i+1)+'.º examen');assert.equal(await p.locator('#ordenMateria option[value="'+id+'"]').count(),0);}
 assert.deepEqual(await p.evaluate(()=>ordenMaterias()),plan);assert.deepEqual(await p.evaluate(()=>materiasOrdenadas().map(m=>m.id)),[...plan,...base.filter(id=>!plan.includes(id))]);await p.locator('#ordenSubir_m_logistica').click();assert.deepEqual(await p.evaluate(()=>ordenMaterias()),['m_logistica','m_historia','m_lre']);
 const lreName=await p.evaluate(()=>CONTENIDO.materias.find(m=>m.id==='m_lre').nombre);await p.getByRole('button',{name:'Quitar '+lreName+' del orden de exámenes',exact:true}).click();assert.deepEqual(await p.evaluate(()=>ordenMaterias()),['m_logistica','m_historia']);await p.getByRole('button',{name:'Listo, empezar a estudiar',exact:true}).click();assert.equal(await p.locator('#ordenMateria').count(),0);await p.getByRole('button',{name:'Cambiar orden de exámenes',exact:true}).click();assert.equal(await p.locator('.orden-lista li').count(),2);await p.getByRole('button',{name:'Listo, empezar a estudiar',exact:true}).click();
 await p.evaluate(()=>navigator.serviceWorker.ready);await p.reload();await login();assert.deepEqual(await p.evaluate(()=>ordenMaterias()),['m_logistica','m_historia']);assert.equal(await p.locator('.materia').first().getAttribute('onclick'),"abrirMateria('m_logistica')");await ctx.setOffline(true);await p.reload();await login();assert.equal(await p.locator('.materia').first().getAttribute('onclick'),"abrirMateria('m_logistica')");await p.getByRole('button',{name:'Cambiar orden de exámenes',exact:true}).click();await p.locator('#ordenBajar_m_logistica').click();assert.deepEqual(await p.evaluate(()=>ordenMaterias()),['m_historia','m_logistica']);await p.getByRole('button',{name:'Listo, empezar a estudiar',exact:true}).click();
 await p.evaluate(()=>pantallaLogin());await create('Otro perfil');assert.deepEqual(await p.evaluate(()=>ordenMaterias()),[]);assert.equal(await p.locator('#ordenMateria').count(),1);assert.deepEqual(await p.evaluate(()=>materiasOrdenadas().map(m=>m.id)),base);await p.getByRole('button',{name:'Ahora no',exact:true}).click();await p.reload();await login();assert.equal(await p.locator('#ordenMateria').count(),0);await p.evaluate(id=>entrarUsuario(id),uid);assert.deepEqual(await p.evaluate(()=>ordenMaterias()),['m_historia','m_logistica']);
 await p.evaluate(()=>{LS.set(KEYORDEN(),['m_logistica','m_logistica','unknown','<img src=x onerror=alert(1)>',{},null]);home();});assert.deepEqual(await p.evaluate(()=>ordenMaterias()),['m_logistica']);assert.equal(await p.locator('.materia').count(),9);assert.equal(await p.locator('.tuti-orden img').count(),0);await p.evaluate(()=>{LS.set(KEYORDEN(),{broken:true});home();});assert.deepEqual(await p.evaluate(()=>ordenMaterias()),[]);assert.equal(await p.locator('.materia').count(),9);
 await p.evaluate(()=>{LS.set(KEYORDEN(),['m_logistica','m_historia']);home();editarOrdenTuti();});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.evaluate(()=>{LS.set('est_tema','oscuro');aplicarTema();});await p.screenshot({path:path.join(repo,'test-results/tuti-orden-celular.png')});assert.deepEqual(errors,[]);console.log('PASS: Tuti prompt, sequential numbering, reorder/remove, stable remaining subjects, per-profile persistence, mobile/dark theme, malformed storage and offline editing');
 }finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
